### ISSUE TITLE
Edge / IE11 No Cookie Disclaimer

### ISSUE THREAD

**Issue by pquerner** [DirkPersky/typo3-dp_cookieconsent#10]
I get the following error in the console from cookie.min.js

```
Expected (
```
Line 6269

Tested against Edge and IE11

This why I dont see the cookie disclaimer in those two browser, since the JS is interrupted. Maybe other browsers have this aswell.

**Comment by DirkPersky** [comment]
ist updated in the new version, thx for reporting
