### ISSUE TITLE
iFrame overlay does not work correctly

### ISSUE THREAD

**Issue by marvinhuebner** [DirkPersky/typo3-dp_cookieconsent#101]
We have the problem that a) the overlay is still displayed although the service in the popup has already been accepted and b) you can't accept the overlay via the button in the overlay but the overlay always remains.

Since the JavaScript is only minified, it is also difficult to debug it.

It looks like `forceAccept` is fired but nothing happens afterwards.

**Comment by DirkPersky** [comment]
The complete code can be find in the NPM Projekt `https://github.com/DirkPersky/npm-dp_cookieconsent/blob/master/src/js/dp_cookieconsent.js`

But how does you iframe look like, maybe there is the issue.

**Comment by yesjoar** [comment]
In `TYPO3 9.5.31` with `dp_cookieconsent 11.2.1` I got exactly the same problem. When I use the linked `https://github.com/DirkPersky/npm-dp_cookieconsent/blob/master/src/js/dp_cookieconsent.js` file everything works fine. So perhaps we should ship a `11.2.2` with the latest `dp_cookieconsent.js`?
