### ISSUE TITLE
php8.1 Log Spaming

### ISSUE THREAD

**Issue by rimmeh8** [DirkPersky/typo3-dp_cookieconsent#105]
Hi, i use  

dp_cookieconsent = 11.6.3
Typo3 = 11.5.19
Php = 8.1

The extension spamms the Typo3 Errorlog with around 100 Errors per Second:

Core: Error handler (FE): PHP Warning: Undefined array key "cookieconsent_status" in /xx/xx/xx/xx/vendor/symfony/expression-language/Node/GetAttrNode.php line 97

**Comment by DirkPersky** [comment]
Are u sure it comes out of my Extension?
Becouse  the string `cookieconsent_status` ist only used in JavaScript not in PHP.

**Comment by DirkPersky** [comment]
Maybe u use `PAD\CookieconsentPluss`?

**Comment by rimmeh8** [comment]
no i only use dp_cookieconstent. i fixed it by blocking the line in symfony as described in the errorlog in line 97. But i dont know exactly where the eroors comes from. i dont have anything else installed related to the topic "cookieconstent_status".
