### ISSUE TITLE
Cookies not deleted after disallowing cookies

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [DirkPersky/typo3-dp_cookieconsent#11]
Thanks for this nice extension, i really like it!

In my testing i have found an issue. I have enabled checkboxes for the cookie banner. If I first allow all cookies all cookies are set, but if i disallow marketing and analytics cookies afterwards, the cookies are still there.  Should the cookies not be deleted after i change this setting?

Test Setup:

Typo3 Version: 8.7.27
PHP Version: 7.2
Operating System: Debian 9
Extension Version: 9.5.6

**Comment by DirkPersky** [comment]
Hello Sebastian,

i don't think.
Because you stop tracking further personal Data, and that is the main reason. 
The Cookie himself has no further functionality.

I also havent read anythink until yet that forces to delete old Cookies.

Greetings

**Comment by lisardo2** [comment]
Hello, 

Does google analytics really not track anymore when the statistic are deactivated but the cookies are not deleted? There is no way the user (and I ...) could know this. 

Greetings

**Comment by DirkPersky** [comment]
After a Page Reload, all further Tracking ist stopped. Because the Analytics Script would not loaded.
When it is correctly implemented.

Anything else you can handle with the Event Messages.

Greetings
