### ISSUE TITLE
TYPO3 12.x Composer Requirement

### ISSUE THREAD

**Issue by weisgerberm** [DirkPersky/typo3-dp_cookieconsent#112]
Hi,

could you fix the statement for the typo3 12.x dependency in your composer.json?

```
"require": {
    "typo3/cms-core": "^10.4.0||^11.5.0||dev-master"
  },
```

Thank you

**Comment by ifre** [comment]
12.2.0 or lower compatible would be great :)

Thank you

**Comment by cbaur** [comment]
Thanks for fixing this. Could you please also create a tagged release from that so we don't have to require dev-master?
