### ISSUE TITLE
Rename files for v12.4 --- @import - setup.txt / constants.txt vs. setup.typoscript / constants.typoscript (#81686 / #82812?)

### ISSUE THREAD

**Issue by skleiber** [DirkPersky/typo3-dp_cookieconsent#114]
I had some problems in activating / loading dp_cookieconsent in current v12 LTS (12.4.0). 
Site uses bolt, in backend no template includes of Extensions.

In sitepackage-EXT i used this includes (without effect):
@import 'EXT:dp_cookieconsent/Configuration/TypoScript/setup.txt'
@import 'EXT:dp_cookieconsent/Configuration/TypoScript/constants.txt'

First test: include in Backend typoscript template ... works, ok (but i need @import for EXT bolt)

For further testing, i copied setup and constants to setup.typoscript and constants.typoscript ... and included them:
@import 'EXT:dp_cookieconsent/Configuration/TypoScript/constants.typoscript'
@import 'EXT:dp_cookieconsent/Configuration/TypoScript/setup.typoscript'

-> this worked

I am not sure, did not find the specific breaking change, but maybe it would be useful to rename .txt to .typoscript or add any hints to documentation.

**Comment by DirkPersky** [comment]
changed
