### ISSUE TITLE
Can't translate labels in TYPO3 12

### ISSUE THREAD

**Issue by timdreier** [DirkPersky/typo3-dp_cookieconsent#116]
Hi, In TYPO3, I can't translate the labels as documented. Doing the following still displays the default text:

```
plugin.tx_dp_cookieconsent {
    _LOCAL_LANG {
        de {
            message = Some german text which are displayed properly
        }
    }
}
```

**Comment by gf-luka** [comment]
I do have the same problem overwriting the labels as described by @timdreier . Tested it with several plugin keys 
`plugin.tx_dp_cookieconsent`
`plugin.tx_dpcookieconsent`
`plugin.dp_cookieconsent`
etc.

I can not even overwrite the whole language files via `locallangXMLOverride`.

Any idea?

**Comment by DirkPersky** [comment]
He,

if i try it this way
```
plugin.tx_dp_cookieconsent._LOCAL_LANG.de {
  allowall = Alle zulassen
  message = TEXT
}
```

Than it works:
![image](https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/1736266/09d6c6f5-28b3-4e61-97f9-3afc2e30fecc)

**Comment by DirkPersky** [comment]
But yeah in TYPO12 it didn't work anymore.

**Comment by kurtzaugg** [comment]
And how could it be realized nowadays?

I cannot translate with overriding the XLF as well. Is that because the plugin folder is not located in typo3_conf/ext?

**Comment by DirkPersky** [comment]
No, u need to change the date in den XLF and than run the languagepack update.
![image](https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/1736266/5f314a2f-4b0c-4536-b33c-47772e125450)


You also coud use the XLF overwrite:

```php
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']
    ['EXT:dp_cookieconsent/Resources/Private/Language/locallang.xlf'][]
        = 'EXT:..YOURPATH...../custom.xlf';
```

https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Localization/ManagingTranslations.html#custom-translations

**Comment by kurtzaugg** [comment]
Thanks, it works now.
