### ISSUE TITLE
dp_cookieconsent breaks leaflet

### ISSUE THREAD

**Issue by timdreier** [DirkPersky/typo3-dp_cookieconsent#123]
Hey,
I just struggled to integrate leaflet. It seems like dp_cookieconsent overwrites the variable L, in which leaflet should be available.

<img width="391" alt="image" src="https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/10117610/2b6e92df-579c-4148-b5e6-143ed610be0b">

Edit: The issue seems to exists since dp_cookieconsent v12.1.0. In dp_cookieconsent v12.0.4 leaflet works fine.

**Comment by DirkPersky** [comment]
I dont know that extension.
I think u postet a screenshot from a JavaScript?

I changed the "https://vitejs.dev/" config hope that now fine.
