### ISSUE TITLE
Error in spanish translation file

### ISSUE THREAD

**Issue by naturefund-falk** [DirkPersky/typo3-dp_cookieconsent#124]
The translation file es.locallang.xlf contains an error causing an xml parsing error in typo3 log
`InvalidXmlFileException: The path provided does not point to an exist
ing and accessible well-formed XML file. Reason: Attribute target-language redefined
 in .../public/typo3conf/ext/dp_cookieconsent/Resources/Private/Language/es.locallang.xlf, line 9, in file .../public/typo3/sysext/core/Classes/Localization/Parser/AbstractXmlParser.php:122 - {"exception":"TYPO3\\CMS\\Core\\Localization\\Exception\\InvalidXmlFileException: The path provided does not point to an existing and accessible well-formed XML file. Reason: Attribute target-language redefined\n in .../public/typo3conf/ext/dp_cookieconsent/Resources/Private/Language/es.locallang.xlf, line 9`

The main reason is the double definition of the  target-language attribute in file tag. I could make a pr for this, but i dont know if there is some kind of automatic code generation for the translation files.

**Comment by naturefund-falk** [comment]
I looked through the other language files, and the same issue is happening on the french translation.

**Comment by DirkPersky** [comment]
Is fixed
