### ISSUE TITLE
Implementation of Consent Mode

### ISSUE THREAD

**Issue by squadt** [DirkPersky/typo3-dp_cookieconsent#127]
Starting March 2024 google consent mode (v2) is required. Is it possible to send these events from the plugin?
https://developers.google.com/tag-platform/security/guides/consent?hl=en#upgrade-consent-v2

**Comment by DirkPersky** [comment]
Thats nothing i need to handle.
But you can do it yourself..

By this way; https://docs.typo3.org/p/dirkpersky/typo3-dp_cookieconsent/main/en-us/Developer/Scripts.html

Or if u added the GoogleTagManager via the config `plugin.tx_cookieconsent.settings.tracking.googleTagManager.id = `
Via listning to the custom events: `dp-cookie-statistics-accept` or `dp-cookie-marketing-accept`

![image](https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/1736266/379150a9-5292-4284-804d-8874bddabbce)
