### ISSUE TITLE
No icons for plugins when adminpanel extension is not loaded

### ISSUE THREAD

**Issue by hannesbochmann** [DirkPersky/typo3-dp_cookieconsent#128]
The icons used for the plugins etc. are registered in ext_localconf.php only if the adminpanel extension is loaded. This is the substitute for the previous check for TYPO3 BE. The registration should be done in the ext_tables.php to have it in the BE only. This way adminpanel doesn't need to be installed.

**Comment by hannesbochmann** [comment]
I tested it in a TYPO3 11.5 with the current version.

**Comment by DirkPersky** [comment]
is changed with 12.2.5
