### ISSUE TITLE
Problems with LocalLang override

### ISSUE THREAD

**Issue by schorsch8878** [DirkPersky/typo3-dp_cookieconsent#129]
Hey,
in Typo3 12.4 an dp_cookieconsent 12.1.4 the override of the language does not work. I have the following in my setup, but nothing happend:

plugin.tx_dp_cookieconsent._LOCAL_LANG {
    de {
        message = Wir verwenden Cookies, um unsere Website und unseren Service zu optimieren.
        dismiss = Alle Cookies zulassen!
        link = Datenschutzerklärung
        deny = Nur notwendige Cookies
      
        # Checkbox labels
        dpRequire = Notwendig
        dpStatistik = Statistiken
        dpMarketing = Marketing

        # Iframe Overlay text
        media.notice = XXX
        media.desc = XXX
        media.btn = XXX
    }
} 

In former Versions there were no problems.

Any ideas?

Many thanks

Georg

**Comment by DirkPersky** [comment]
Its a TYPO3 issue.

#116 (here is workaround)
#125
