### ISSUE TITLE
Incompatible with TYPO3 8.7.x?

### ISSUE THREAD

**Issue by Aero91** [DirkPersky/typo3-dp_cookieconsent#13]
I've installed the newest version of dp_cookieconsent from TER in a couple of systems running 8.7.x. The cookie banner won't show up with the provided example Typoscript here on github. Do I fail to notice some necessary settings, or is there an issue?

**Comment by DirkPersky** [comment]
Hi @Aero91 
i think it shoud be the same as "Scripts not loaded in Typo3 6.2 #8"

**Comment by DirkPersky** [comment]
maybe there is a other, Plug-In or your template thats override the.
`page.headerData.998`

or you you dont used the `page `value for your Template.

_Originally posted by @DirkPersky in https://github.com/DirkPersky/typo3-dp_cookieconsent/issues/8#issuecomment-527523936_

**Comment by Aero91** [comment]
Problem solved - thanks.
