### ISSUE TITLE
Cross Domain Cookie Consent | Frage

### ISSUE THREAD

**Issue by lillijahn** [DirkPersky/typo3-dp_cookieconsent#130]
Gäbe es eine Möglichkeit mit dem Plug-In [Cross-Domain-Cookie-Consent ](https://support.cookiebot.com/hc/en-us/articles/360003792573-Cross-domain-Consent-Sharing#h_01FHYYNCTCWZRRFJYTD6AKBC5E) zu ermöglichen? 

Es geht in unserem konkreten Fall nicht um Subdomains, sondern tatsächlich um zwei 'unabhängige' Domains (example.de & example.com).

Vielen Dank schon mal! :)

**Comment by DirkPersky** [comment]
Hallo,

nein leider nicht.
