### ISSUE TITLE
Question about translations

### ISSUE THREAD

**Issue by hthurmann** [DirkPersky/typo3-dp_cookieconsent#134]
ist there a possibility to translate the cookie descriptions also? For me it makes less sense to translate only the labels.

b.r.

hanno

**Comment by DirkPersky** [comment]
plugin.tx_dp_cookieconsent._LOCAL_LANG.de.message = ...
![image](https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/1736266/72ced33a-6d79-413f-83da-25b98a759a3a)
This or what did you mean?

**Comment by hthurmann** [comment]
No - thats very clear. But i can't find a possibility to tranaslate the description of the cookies themselve
![grafik](https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/162693498/22161a69-69f8-49a6-952f-71c07c219e1e)

**Comment by DirkPersky** [comment]
U coud define a seperate storage Folder for translations and set it based on the selected Language `lib.dp_cookieconsent.settings.storagePid = `.
I did it becouse my customer have seperate analytics account per language.
