### ISSUE TITLE
calling javascript resources

### ISSUE THREAD

**Issue by hthurmann** [DirkPersky/typo3-dp_cookieconsent#137]
Example: <script data-ignore="1" data-cookieconsent="statistics"  data-src="https://maps.googleapis.com/maps/api/js?key={settings.map.googleMaps.key}&language=de&callback=Function.prototype" type="text/plain"></script>

this code results in a not being loaded script - even if the cookie is accepted.

**Comment by DirkPersky** [comment]
For me it works:
![image](https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/1736266/9138b216-99df-499d-857e-5d44b6c128df)

Which version do you use?
Have u maybe an JavaScript error in your browser console?
