### ISSUE TITLE
How to deal with "fe_typo_user"-Cookie from TYPO3 Core ?

### ISSUE THREAD

**Issue by m10a** [DirkPersky/typo3-dp_cookieconsent#14]
How can I handle the "fe_typo_user"-Cookie with this Tool, which is used for frontend user login by TYPO3 itself? As I can see I only can manipulate how local or external JavaSript-Files or -snippets will be included. Is that even possible with this solution?

**Comment by DirkPersky** [comment]
Hello @m10a

no you can't handle the `fe typo3 user` Cookie, but because that cookie is a necessary one, i think you dont need to.
