### ISSUE TITLE
Some cookies cannot be revoked

### ISSUE THREAD

**Issue by regioadmin** [DirkPersky/typo3-dp_cookieconsent#140]
If I accept all cookies and revoke them afterwards. Some cookies still there after reloading the page.
For example the Facebook pixel cookie _fbp  defined as "statistics", field domain is empty.

By the way what about information stored in "Local Storage", is it possible to prevent it from being saved with your tool?

![grafik](https://github.com/DirkPersky/typo3-dp_cookieconsent/assets/3864439/9f38b547-7e6c-4432-98b2-1321dc153628)

**Comment by DirkPersky** [comment]
He!

The cookies themselves will not be deleted.
**BUT if you have properly integrated the services, you prevent them from being executed!**
For example: if Google Analytics will not be executed anymore, so the cookies can still exist. Since they are not sent to Google.

**Comment by DirkPersky** [comment]
If you want, you can write a script that is listening to an event and will remove the Cookies.

```js
document.addEventListener('dp--cookie-revoke', function (e) {
    // YOUT Custom Script to Remove the Cookies
});
```
