### ISSUE TITLE
Language overrides not working in 12.2.6

### ISSUE THREAD

**Issue by ursbrauchli** [DirkPersky/typo3-dp_cookieconsent#148]
I added the TS as described here: https://docs.typo3.org/p/dirkpersky/typo3-dp_cookieconsent/main/en-us/Configuration/Language.html

… and changed the title as well as the dpStatistik, dpRequire and media.notice values:

E.g.: 

```
plugin.tx_dp_cookieconsent._LOCAL_LANG {
    de {
        message = Diese Website verwendet Cookies und Targeting Technologien, um Ihnen ein besseres Internet-Erlebnis zu ermöglichen und die Werbung, die Sie sehen, besser an Ihre Bedürfnisse anzupassen. Diese Technologien nutzen wir außerdem, um Ergebnisse zu messen, um zu verstehen, woher unsere Besucher kommen oder um unsere Website weiter zu entwickeln.
        dpStatistik = Statistik
        dpRequire = Benötigt
        media.notice = Ihre Privatsphäre ist uns wichtig!
    }
}
```
But only the message is shown in the cookie-banner. The other three are ignored.

**Comment by rubensutter** [comment]
I would suggest trying to change plugin.tx_dp_cookieconsent._LOCAL_LANG { to plugin.tx_dpcookieconsent._LOCAL_LANG { according to the provided variables in the setup config file and try if it works. I think the part dp_cookieconsent changed to dpcookieconsent without "_" for the newer or updated versions like 12.2.6 or 13.0.0 for TYPO3 v12.

**Comment by DirkPersky** [comment]
It was a TYPO3-Core Bug in older versions that u cant use _LOCAL_LANG
