### ISSUE TITLE
Remove statistic cookies after decline

### ISSUE THREAD

**Issue by Afshinge** [DirkPersky/typo3-dp_cookieconsent#150]
Actually, I've thought that statistic cookies, which are first accepted, are deleted after decline. 
I use Matomo in a typo3 12.4.16 installation with dp_cookieconsent 12.2.6. But even at https://dp-wired.de this doesn't work as accepted.

reloadOnRevoke = true, type = optin - or do I miss some settings? thanks for any help!

The Dynamic Ajax Content works fine with accepting and declining!!

**Comment by DirkPersky** [comment]
Hello,

The cookies themselves won't be removed, but if you implement your JavaScript correctly, the scripts won't load.

This means:
- If cookies are accepted, the Matomo scripts will load.
- If cookies are declined, the scripts won't load.

Greetings
