### ISSUE TITLE
Page reload on grant

### ISSUE THREAD

**Issue by Make66** [DirkPersky/typo3-dp_cookieconsent#157]
There is this feature of page-reload-on-revoke (plugin.tx_cookieconsent.settings.reloadOnRevoke). 
My usecase is built the other way around: reloadOnGrant. 
There is no cookie coming where I might attach the script to be loaded. Only a page-reload does help.
Is there a feature I did oversee? 
I could hack dp_cookieconsent.js and add some JS to it, but I bet there is a more elegant way of a page-reload on grant?

**Comment by Make66** [comment]
Researching the events (see docs) seemed helpful. Unfortunately, "dp--cookie-revoke" IS fired, when I remove a checkbox, but it doesn't tell which one. So reading the cookie "dp_cookieconsent_status" from js and parsing the content looks like the solution.

**Comment by DirkPersky** [comment]
Hey, you could check the cookie, but essentially, that's what the page reload is for.
![image](https://github.com/user-attachments/assets/f688546a-2bdf-4056-82cb-840ba67dde21)
If everything is integrated correctly, the corresponding script won't be loaded afterward.
