### ISSUE TITLE
Typo in group name

### ISSUE THREAD

**Issue by mario-seidel** [DirkPersky/typo3-dp_cookieconsent#16]
This should be "required", I think.

https://github.com/DirkPersky/typo3-dp_cookieconsent/blob/f0489e66c28b75db077fe85807e203aa765dce82/Resources/Public/JavaScript/cookie.js#L134

**Comment by DirkPersky** [comment]
#17

**Comment by mario-seidel** [comment]
@DirkPersky can you add the minimized version of cookie.js too? Thanks
