### ISSUE TITLE
composer installation fails

### ISSUE THREAD

**Issue by pquerner** [DirkPersky/typo3-dp_cookieconsent#18]
When I install this extension via `composer req` it resolves to a directory named `ext/typo3_dp_cookieconsent` - which is not resolvable via TS like this `EXT:dp_cookieconsent/Resources/Private/Layouts/Cookie.html`. Is there something wrong about composer on my end or should this be added to the extensions composer.json that its directory name is without `"typo3-"` prefix (if there is such configuration available)

**Comment by DirkPersky** [comment]
He @pquerner 

now it shoud work.

Greetings
