### ISSUE TITLE
Language-Files

### ISSUE THREAD

**Issue by Chriz74** [DirkPersky/typo3-dp_cookieconsent#2]
I try to adjust the text for the messages.  

> plugin.tx_cookieconsent._LOCAL_LANG.de {  
>	  message = myMessage  
>	  dismiss = myDismiss  
	  link = myLink  
}  

does not work for me.

**Comment by DirkPersky** [comment]
you shoud use the right extension name
```
plugin.tx_dp_cookieconsent._LOCAL_LANG {
    de {
        message = XXX
        dismiss = XXX
        link = XXX
    }
}
```

I added it in the dokumentation _THX_
