### ISSUE TITLE
Custom Checkbox Layout

### ISSUE THREAD

**Issue by Nesfiran** [DirkPersky/typo3-dp_cookieconsent#20]
It is not possible to create an individual layout for checkboxes. 
Can I extend the Javascript so that I can use an individual layout?

`<label for="dp--cookie-require">
<input type="checkbox" id="dp--cookie-require" class="dp--check-box" disabled="disabled" checked="checked">
<span class="custom-checkbox"></span>
</label>`

**Comment by DirkPersky** [comment]
He @Nesfiran 

in the current version it is not posible, but i take the request on the ToDO list.

Greetings
Dirk

**Comment by Nesfiran** [comment]
Hello, Dirk,

Thank you so much for your feedback.
I would welcome this feature.

Greetings

**Comment by DirkPersky** [comment]
@mario-seidel thx for your support.
@Nesfiran At the end of this week I want to release a new version with this feature and #12
