### ISSUE TITLE
disable auto open cookie popup on loading

### ISSUE THREAD

**Issue by mario-seidel** [DirkPersky/typo3-dp_cookieconsent#27]
The cookie consent library has an option called autoOpen. It would be nice to be able to configure it in the extension.
If you have the cookie popup as an overlay for the entire site, you want to disable it on your privacy page. Even if you have some kind of init process on your site and want to activate the popup yourself.

**Comment by DirkPersky** [comment]
thx 4 your active work

**Comment by mario-seidel** [comment]
Thank you for the quick acceptance of PRs :+1:
