### ISSUE TITLE
How to remove unneccesary checkboxes

### ISSUE THREAD

**Issue by m10a** [DirkPersky/typo3-dp_cookieconsent#29]
How can I remove an unneccesary checkbox like "marketing", if I don't need it?

If I remove the label in the partial, I geht the following errors in the Javascript Console:

"Uncaught TypeError: Cannot set property 'checked' of null"
"Uncaught TypeError: Cannot set property 'id' of null"

Do I have to deactivate the Checkbox anywhere else in Typoscript?

**Comment by m10a** [comment]
How can I remove an unneccesary checkbox like "marketing", if I don't need it?

If I remove the label in the partial, I geht the following errors in the Javascript Console:

"Uncaught TypeError: Cannot set property 'checked' of null"
"Uncaught TypeError: Cannot set property 'id' of null"

Do I have to deactivate the Checkbox anywhere else in Typoscript?

**Comment by DirkPersky** [comment]
he for that you need to remove that setting from the [typoscript](https://github.com/DirkPersky/typo3-dp_cookieconsent/blob/master/Configuration/TypoScript/setup.txt)

`page.headerData.998.settings.checkboxes.marketing >`
^^ i hope that works, dont tested.

**Comment by m10a** [comment]
> he for that you need to remove that setting from the [typoscript](https://github.com/DirkPersky/typo3-dp_cookieconsent/blob/master/Configuration/TypoScript/setup.txt)
> 
> `page.headerData.998.settings.checkboxes.marketing >`
> ^^ i hope that works, dont tested.

This does not work. Error keeps the same.
Imo this setting is responsible for prefilling of the checkbox not for deactivating of it.

**Comment by DirkPersky** [comment]
'lib.dp_cookieconsent.settings.checkboxes.marketing >'  than shoud remove the prefill.

**Comment by m10a** [comment]
I don't want to remove the prefill, but the checkbox itself. If I do this in the fluid partial, I get the error mentioned above.

**Comment by DirkPersky** [comment]
yeah i know and that remove of the prefill shoud fix you error

**Comment by DirkPersky** [comment]
i tried it today (with the new dev version) and that works with

typoscript
```
lib.dp_cookieconsent.settings.checkboxes.marketing >
```

template
```html
<div class="dp--cookie-check" xmlns:f="http://www.w3.org/1999/html">
    <label for="dp--cookie-require">
        <f:form.checkbox id="dp--cookie-require" class="dp--check-box" value="" disabled="disabled" checked="true" />
        <f:translate key="dpRequire" extensionName="dp_cookieconsent" />
    </label>
    <label for="dp--cookie-statistics">
        <f:form.checkbox id="dp--cookie-statistics" class="dp--check-box" checked="{settings.checkboxes.statistics}" value="" />
        <f:translate key="dpStatistik" extensionName="dp_cookieconsent" />
    </label>
</div>

```

**Comment by DirkPersky** [comment]
shoud work with the last release too

**Comment by m10a** [comment]
> i tried it today (with the new dev version) and that works with
> 
> typoscript
> 
> ```
> lib.dp_cookieconsent.settings.checkboxes.marketing >
> ```
Hi, with this it works for me too. Thanks! Can you include it in the docu?

**Comment by DirkPersky** [comment]
I hope this is fine for you

## F.A.Q.
Some F.A.Q. can be found [here](https://github.com/DirkPersky/typo3-dp_cookieconsent/wiki)

**Comment by m10a** [comment]
oh, not just for me but for anybody who run in the same problem ;-)

I think it would be better, if you place it in the "Dynamic Checkboxes"-Section of your Readme. Who takes note of the Wiki?

And no, it's not just about the "preffill" It's about removing the entire checkbox. I think you should not only describe in your Readme, how one can add a checkbox  but also how to remove one.

**Comment by p410n3** [comment]
> I think it would be better, if you place it in the "Dynamic Checkboxes"-Section of your Readme. Who takes note of the Wiki?

May I propose to link the wiki in the README? A wiki is very comfortable, as putting every edge-case inside the README makes it quite messy. This way people *will* take note of the wiki.

Kind regards,

Phillip
