### ISSUE TITLE
includeJSFooter (dp_cookieconsent.js is not included)

### ISSUE THREAD

**Issue by whiteroom** [DirkPersky/typo3-dp_cookieconsent#30]
dp_cookieconsent.js might fail to include with given version parameter

affects Configuration >  TypoScript > setup.txt
TYPO3 CMS Version 9.5.13
PHP 7.2.23

Solution: Leave away version when including JS in footer

Change
 `    includeJSFooter {
        dp_cookieconsent = EXT:dp_cookieconsent/Resources/Public/JavaScript/dp_cookieconsent.js?v=10.2.0
    }`

to proposed:
 `    includeJSFooter {
        dp_cookieconsent = EXT:dp_cookieconsent/Resources/Public/JavaScript/dp_cookieconsent.js
    }`

**Comment by DirkPersky** [comment]
thx for the info, fixed it.
