### ISSUE TITLE
Safari reports unexpected token in cookie.min.js

### ISSUE THREAD

**Issue by SilentHunter124** [DirkPersky/typo3-dp_cookieconsent#31]
When trying to close consent it tells:
cookie.min.js: Line 51:69 Unexpected token '<'

I am running typo3 9.5.13 with dp_cookieconsent version 10.2.0

![image](https://user-images.githubusercontent.com/1576808/71805456-96061580-3066-11ea-9e6a-8e82a63c9581.png)

**Comment by SilentHunter124** [comment]
Found out what was causing the problem, but I don't know why. For windows tiles (bookmarks) I am using this snippet to color the tile of the bookmark:

` 
   90.value = <meta name="msapplication-TileColor" content="#00a300">`

But somehow this causes problems with this plugin. So I removed that line.

**Comment by DirkPersky** [comment]
Hello @SilentHunter124 

thank for the info. I will create a fix for that.

It lines up with [setup.txt LINE: 110](https://github.com/DirkPersky/typo3-dp_cookieconsent/blob/master/Configuration/TypoScript/setup.txt)

you can change your line number from 90.value to 91.value and than all will work.
