### ISSUE TITLE
Revoke button as text link?

### ISSUE THREAD

**Issue by djrocher** [DirkPersky/typo3-dp_cookieconsent#32]
I would like to call the revoke function by using a text link (or button) in the footer instead of the revoke button (which overlays with the "To top arrow" on my website).

I mean something like:
`<a href="#" title="Cookie settings" onclick="FunctionName();return false;">Cookie settings</a>`

How would the correct syntax be? And will it work when the revoke function is disabled by using
plugin.tx_cookieconsent.settings.revokable = false

By the way:
plugin.tx_cookieconsent.settings.revokable = false
doesn't work for me (dp_cookieconsent 10.3.0, TYPO3 8.7.30), although it should work (https://github.com/DirkPersky/typo3-dp_cookieconsent/issues/9)? The revoke button does not disappear.

Kind regards and thanks for your extension. The documentation and compatibility with so many TYPO3 versions is great :-)

**Comment by DirkPersky** [comment]
As i see in CookieConsent is this rule
```javascript
// revokable is true if advanced compliance is selected
if (this.options.type != 'info') this.options.revokable = true;
```
though u cant disable the revoke Button with a extendes Layout.

But u can do it via CSS, an with this onlick event it shoud open again.
```javascript
window.DPCookieConsent.popup.revokeChoice();
```

**Comment by djrocher** [comment]
Thank you, it works! I'm hiding the revoke button by setting `.cc-revoke` to `display: none;` (CSS) and use a text link to call the revoke function:

`<a href="#" title="Cookie settings" onclick="window.DPCookieConsent.popup.revokeChoice();">Cookie settings</a>`

Regarding usability I prefer this way, because the new revoke button (fingerprint) doesn't say what it's for (the Default Cookie Consent Button is still available in the partial CookieRevoke.html).

**Comment by DirkPersky** [comment]
Okay, i will update it. With the version on my website.
