### ISSUE TITLE
Class 'TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper' not found

### ISSUE THREAD

**Issue by peerlight** [DirkPersky/typo3-dp_cookieconsent#36]
in dp_cookieconsent/Classes/ViewHelpers/JsonViewHelper.php line 17
on TYPO3 10.3.0
with dp_cookieconsent 10.4.2 and 10.5.0

see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Deprecation-87277-FluidClassAliases.html

**Comment by DirkPersky** [comment]
Hey, thank for that hint.

Can u try the latest dev-master Version?

**Comment by peerlight** [comment]
Thanks, current master is ok.
