### ISSUE TITLE
English translations texts for cookie consent not set although set in TS

### ISSUE THREAD

**Issue by micron** [DirkPersky/typo3-dp_cookieconsent#39]
I was trying to set the english consent text as described in the documentation. Unfortunately, the english texts are ignored although they're set in Typoscript. The german texts work as they should.

My TS Setup:

```
plugin.tx_dp_cookieconsent {
	_LOCAL_LANG {
		de {
			message = Some german text which are displayed properly
		}
		en {
			message = English text is ignored
		}
	}
}
```

My environment:

dp_cookieconsent@10.5.1
TYPO3@9.5.16
PHP 7.2

**Comment by DirkPersky** [comment]
use instead of "**en**" the "**default**" than it should work.

**Comment by DirkPersky** [comment]
```
plugin.tx_dp_cookieconsent {
	_LOCAL_LANG {
		de {
			message = Some german text which are displayed properly
		}
		default {
			message = English text 
		}
	}
}
```

**Comment by micron** [comment]
Worked liek a charm. Thank you!
