### ISSUE TITLE
current cookie.js is NOT gdpr-compliant!

### ISSUE THREAD

**Issue by mtness** [DirkPersky/typo3-dp_cookieconsent#4]
FYI, the cookie.js script has to load additional stuff from a hardcoded cloudflare address^^

**Comment by DirkPersky** [comment]
Hi @mtness 

that it not completly right:
https://www.cloudflare.com/gdpr/introduction/
https://blog.cloudflare.com/advancing-privacy-protection-with-the-gdpr/

cloudflare does a lot to prove that fakt, and you has the option to signature a GDPR-DPA.

---

On the other hand, it is also very questionable whether the courts will ban CDNs. After all, they are in the interest of the user and ensure an optimized loading time.

As well as the resources are cached for 10 years, and after the one-time call not reloaded but delivered from the cache.

Therefore, it is quite questionable whether such a thing in a caution really provide a sufficient basis.

---

But I observe the current warnings and will act at latest at a corresponding court judgment.

Apart from that, I have already thought about an appropriate integration of the two CDN ressources, and wanted to make it available in the next version.

Greetings
Dirk
