### ISSUE TITLE
How to locate the Buttons below?

### ISSUE THREAD

**Issue by SteffN82** [DirkPersky/typo3-dp_cookieconsent#40]
Hi there!
Tried your extension the first time in Typo3 7.6.43 and 9.5.18 and I'm happy. ;)

But there are two issues I tried to solve:
1. How can I locate the buttons (allow / allow all etc.) the user had to click (in german f.e.)?
2. Is the fingerprint showed after clicking necessary or is it possible to remove it?

It would be great to know. Thank you very much for helping and for this great extension.

Greetings Steff

**Comment by SteffN82** [comment]
Ok, found the fingerprint (adds button to review the consent), would be great to get a hint for noobs like me ^^

Still need help to translate the buttons.

**Comment by DirkPersky** [comment]
https://github.com/DirkPersky/typo3-
dp_cookieconsent/blob/master/Documentation/translation.md

add in you TypoScript:
```
plugin.tx_dp_cookieconsent._LOCAL_LANG {
    de {
        message = XXX
        # Buttons
        dismiss = XXX
        deny = XXX
        allowall = XXX

        # Checkbox labels
        dpRequire = XXX
        dpStatistik = XXX
        dpMarketing = XXX
    }
}
```

**Comment by SteffN82** [comment]
Great! Thank you very much. ;)
