### ISSUE TITLE
revokable = false has no effekt

### ISSUE THREAD

**Issue by criwe** [DirkPersky/typo3-dp_cookieconsent#44]
Hi!
The setting plugin.tx_cookieconsent.settings.revokable = false hast no effekt, the "revoke button" still occurs.
Best,
Christoph

**Comment by DirkPersky** [comment]
https://www.osano.com/cookieconsent/documentation/javascript-api/#revoke_options

**Comment by criwe** [comment]
Ah, understand, thanks!
