### ISSUE TITLE
Revoke botton not usable with mobile devices

### ISSUE THREAD

**Issue by criwe** [DirkPersky/typo3-dp_cookieconsent#45]
Hi!
The revoke-button is not usable on mobile devices (tested with an Android and iPhone). When tapping an the icon just nothing happens.

TYPO3 9 + 10 (actual versions).

Best,
Christoph

**Comment by DirkPersky** [comment]
I tried it with a "Samsung S10" on a fresh TYPO 10 in this moment.
everything worked there as expected

**Comment by criwe** [comment]
hi!
I've testet it on another site, there it works fine.. so I think its a templating thing. I close this ticket, when I find the reason I will comment here.
Best,
Christoph

**Comment by criwe** [comment]
Reason in my case was an old "jQuery UI Touch Punch" / "jquery.finger - v0.1.4"-Plugin.
Removing theses -> evrything works like expected :-)
