### ISSUE TITLE
Checkbox statistics is always checked

### ISSUE THREAD

**Issue by herrhamann** [DirkPersky/typo3-dp_cookieconsent#46]
Hi,
there is no effect when setting plugin.tx_cookieconsent.settings.statistics = false. The stistics checkbox is always checked. Tried with versions 10.0.0 up to 10.5.2.

Best regards
Alex

**Comment by DirkPersky** [comment]
Sure that works, but i can be the Cache of your Template, 
![image](https://user-images.githubusercontent.com/1736266/83878038-cba94a80-a73b-11ea-9fc1-fef3a7fe8fe7.png)


or an old Cookie
![image](https://user-images.githubusercontent.com/1736266/83877983-b6ccb700-a73b-11ea-9c6c-0ad52affc7cf.png)
