### ISSUE TITLE
cookieconsent_status-Cookie has no SameSite-Attribute

### ISSUE THREAD

**Issue by MoppieMop** [DirkPersky/typo3-dp_cookieconsent#47]
FireFox and Chrome say they will ignore these cookies in future releases.

**Comment by DirkPersky** [comment]
Can give me a Screenshot witch Cookies you mean?
Because all sites i testet don't give me a hit about the PlugIn cookies, only 3rd party cookies.

**Comment by MoppieMop** [comment]
Sorry, i can't find the message anymore. I don't know why it was shown in first place.
