### ISSUE TITLE
absRefPrefix is not appended

### ISSUE THREAD

**Issue by stucki** [DirkPersky/typo3-dp_cookieconsent#5]
Commit 2d26dd56f22031ca6919325cd9709742209f56b0 sets options for the JavaScript snippet with references to the JS and CSS code. This reference is relative, which means it will fail on the following site: https://mysite/de/.

This fails because the browser will attempt to load https://mysite/de/typo3conf/ext/... which doesn't exist.

**Comment by DirkPersky** [comment]
Yeah, I think that's more a problem of TYPO3 himself.

If I put `config.absRefPrefix = /de/` on my page, then nothing works anymore. 
- no pictures are displayed
- no CSS is loaded 
- no JS is loaded too

Apart from that realUrl recommends setting this to `config.absRefPrefix = /`
In de last 6 Years i never got a Projekt where i had to change that.

Although, if you're using such a configuration, I think you'll get to load of the right knowledge to know how  `<f:uri.resource path="JavaScript/cookieconsent.min.js" extensionName="dp_cookieconsent" />`  will link the right ressources.

Though let me know what to doo.

**Comment by DirkPersky** [comment]
He it is fixed and released in the new version.

**Comment by stucki** [comment]
Wow, that's fast! Many thanks for fixing this. Looks good to me know.
