### ISSUE TITLE
Contradictory licensing: GPL vs. AGPL?

### ISSUE THREAD

**Issue by martin-helmich** [DirkPersky/typo3-dp_cookieconsent#52]
I noticed that this repo's [LICENSE file](https://github.com/DirkPersky/typo3-dp_cookieconsent/blob/master/LICENSE) contains a copy of the AGPL 3.0, whereas both [README.md](https://github.com/DirkPersky/typo3-dp_cookieconsent/blob/master/README.md) and [composer.json](https://github.com/DirkPersky/typo3-dp_cookieconsent/blob/master/composer.json) say "GPL 3.0 or later".  Can you clarify under which license this extension is actually available?

**Comment by DirkPersky** [comment]
AGPL sorry
