### ISSUE TITLE
CSS property `left` uses 'unset' instead of 'auto'

### ISSUE THREAD

**Issue by rintisch** [DirkPersky/typo3-dp_cookieconsent#53]
For styling the revoke button the properties `left` or `right` are used. 

To unset one of these values e.g. `left: unset;` is used. `left: auto;` would be correct. 

The usage of the value `unset` renders the revoke button incorrectly in IE11 (see screenshot).

__Usage of `left: unset;` in IE 11:__
![grafik](https://user-images.githubusercontent.com/44193208/90633455-5d4a3380-e226-11ea-9fbb-2d5d72c1ef97.png)

__Usage of `left: auto;` in IE 11:__
![grafik](https://user-images.githubusercontent.com/44193208/90634058-6be51a80-e227-11ea-8c6e-e1bb16e87844.png)

**Comment by DirkPersky** [comment]
thx for reporting =)
