### ISSUE TITLE
Conflicts with Cypress

### ISSUE THREAD

**Issue by Padina14** [DirkPersky/typo3-dp_cookieconsent#60]
In Production, it works fine.
For the future I want to build acceptance-Tests with Cypress.  
If iI use Cypress, the message-box will not be shown. I thinke there is a conflict between your JavaScript-code and the cypress-runner 
I Use TYPO3 9.5.22 and your version "version": "10.6.1" (Composer.lock)

Have you a solution for that?
Is there a chance, to get an un-compressed javascript-code, soi can check the problem myself?
Dieter

**Comment by DirkPersky** [comment]
He Dieter,

you can take a look into the NPM project, there u can find all dev files:

https://github.com/DirkPersky/npm-dp_cookieconsent/blob/master/src/js/cookie.js

Greetings
Dirk

**Comment by Padina14** [comment]
Thanks for your quick answer. I Hope it will help to solve my problem, to check the acceptance automatically the cookie-consent with cypress

With best regards
    Dieter


--
Dr. Dieter Porth
Web/Entwicklung

porth@monsun-media.com<mailto:porth@monsun-media.com>

monsun media GmbH
Lange Straße 3 | 49080 Osnabrück
T 0541406964-0 | F 0541 406964-9

M-Lab
Konsul-Smidt-Straße 8d | 28217 Bremen

www.monsun-media.com

Geschäftsführer: Katarina Breves, Michael Hantke
Amtsgericht Osnabrück | HRB 20969


Von: Dirk Persky <notifications@github.com>
Antworten an: DirkPersky/typo3-dp_cookieconsent <reply@reply.github.com>
Datum: Montag, 16. November 2020 um 16:21
An: DirkPersky/typo3-dp_cookieconsent <typo3-dp_cookieconsent@noreply.github.com>
Cc: Dieter Porth <porth@monsun-media.com>, Author <author@noreply.github.com>
Betreff: Re: [DirkPersky/typo3-dp_cookieconsent] Conflicts with Cypress (#60)


He Dieter,

you can take a look into the NPM project, there u can find all dev files:

https://github.com/DirkPersky/npm-dp_cookieconsent/blob/master/src/js/cookie.js

Greetings
Dirk
