### ISSUE TITLE
Position in source code

### ISSUE THREAD

**Issue by rteinze** [DirkPersky/typo3-dp_cookieconsent#63]
Please add an option to decide to include the source code either at top or at the bottom of the <body> area.

There are issues in Google results with the texts and labels from the extension. Please look at the screenshot.

![Screenshot 2021-01-14 114245](https://user-images.githubusercontent.com/38670243/104580883-1db13780-565e-11eb-9678-1adae8d216df.png)

Thanks a lot for your nice extension.

**Comment by riegeo** [comment]
We have the same issue. This especially happens if there is no description (or empty) tag.


Thank you
