### ISSUE TITLE
Cross Domain tracking

### ISSUE THREAD

**Issue by Nesfiran** [DirkPersky/typo3-dp_cookieconsent#64]
We want to use cross-domain tracking is this possible?

I made a short test with `this.cookie = {
 domain: 'domain1,domain2'
};` but without success.

**Comment by DirkPersky** [comment]
You can not set Cookies for another domain, because it may cause serious security issue. But if all domains are under your control, you may use some redirect way at server side to realize it.

https://stackoverflow.com/questions/3342140/cross-domain-cookies
