### ISSUE TITLE
DOMContentLoaded event nach XHR loaded

### ISSUE THREAD

**Issue by R-Grimme** [DirkPersky/typo3-dp_cookieconsent#66]
Wir laden Content mit YouTube-Videos per AJAX nach und müssten den Event, der die iFrame-Overlays erzeugt, darum nochmals manuell feuern. 

Gibt es eine Methode, um die (roten) Overlays zu einem beliebigen Zeitpunkt - in unserem Fall, nachdem die nachgeladenen Videos vorhanden sind - manuell setzen zu lassen?

**Comment by DirkPersky** [comment]
Ihr habt die Möglichkeit mit der 10.7.0 Version den Händler dafür nach eurem XHR request aufzurufen  `window.DPCookieConsent.overlays();`

**Comment by R-Grimme** [comment]
Vielen Dank für die schnelle Lösung!! 
Wir konnten unser Anliegen umsetzen.
