### ISSUE TITLE
Impossible to comply with license terms

### ISSUE THREAD

**Issue by dotdash** [DirkPersky/typo3-dp_cookieconsent#67]
The GPLv3 says that when conveying the software, you must make the source code available. According to the GPL FAQ, client side JavaScript falls under conveying the software, and the source code is defined as:

> The "source code" for a work means the preferred form of the work for making modifications to it.

But there's only a minified JS file, which doesn't really seem to qualify for this defintion, which also means that clause 6. "Conveying Non-Source Forms" applies.

So it seems impossible to me to comply with the license under these conditions and I'd kindly ask you to provide the actual source code alongside the minified version.

Btw, the minified file claims to be licensed under GPL v3+ and refers to a URL that ends up with a 404 response. And the `LICENSE.md` file contains the AGPLv3. That doesn't fit well either.

**Comment by DirkPersky** [comment]
https://github.com/DirkPersky/npm-dp_cookieconsent

you can finde the unminified JS

**Comment by dotdash** [comment]
Thanks!
