### ISSUE TITLE
revokable = false gibt trotzdem cc-revoke im HTML aus

### ISSUE THREAD

**Issue by landwire** [DirkPersky/typo3-dp_cookieconsent#69]
Ich hätte erwartet, dass, wenn man revokable auf false setzt, das HTML für "cc-revoke dp--revoke cc-bottom cc-animate" nicht mehr ausgegeben wird. Bei uns wird es jedoch weiterhin ausgegeben.
Version ist 10.7.0

**Comment by DirkPersky** [comment]
#44 here u can find more information about it.
