### ISSUE TITLE
includeJSFooter

### ISSUE THREAD

**Issue by jimihuy** [DirkPersky/typo3-dp_cookieconsent#7]
How block this url?

`includeJSFooter {
gmaps = https://maps.googleapis.com/maps/api/js?key=AIz...
gmaps.async = 1
    }`

**Comment by DirkPersky** [comment]
He @jimihuy

**Comment by DirkPersky** [comment]
He @jimihuy 

you can add it in the header with plain text:
```
page.headerData.6571 = TEXT
page.headerData.6571.value = https://maps.googleapis.com/maps/api/js?key=AIz..
page.headerData.6571.wrap = <script data-ignore="1" data-cookieconsent="statistics" type="text/plain" src="|"></script>

```

**Comment by DirkPersky** [comment]
the important part is `data-cookieconsent="statistics" type="text/plain"`
