### ISSUE TITLE
Wie kann ich verhindern, dass folgende Klasse ausgegeben wird: cc-color-override-xxxxxxx?

### ISSUE THREAD

**Issue by landwire** [DirkPersky/typo3-dp_cookieconsent#70]
Auch mit einer einfachen Konfiguration scheint immer diese Klasse mitgegeben zu werden. Kann man das irgendwie unterdrücken?

**Comment by mxwssl** [comment]
> Auch mit einer einfachen Konfiguration scheint immer diese Klasse mitgegeben zu werden. Kann man das irgendwie unterdrücken?

Nein, du kannst aber in deiner constants.txt die entsprechenden CSS-Werte leeren
`plugin.tx_cookieconsent.settings.palette.popup {
	background >
	text >
}`
