### ISSUE TITLE
cookie.min.js?v=10.0.0 not found

### ISSUE THREAD

**Issue by Aero91** [DirkPersky/typo3-dp_cookieconsent#73]
Hi,

I just noticed that the extension is trying to load a javascript file that does not exist. However, everything is working correctly.

typo3conf/ext/dp_cookieconsent/Resources/Public/JavaScript/cookie.min.js?v=10.0.0

Extension Version: 11.0.0
TYPO3: 9.5.28 without composer

**Comment by DirkPersky** [comment]
Have u used an older Version before?
Because in Version 10.2 the JS path has changed.

**Comment by Aero91** [comment]
Yes, I'm using this extension for about two years now.
