### ISSUE TITLE
Changes from December 2021 - TTDSG

### ISSUE THREAD

**Issue by landwire** [DirkPersky/typo3-dp_cookieconsent#79]
Hi there,
from the 1st of December some legal changes will come to effect with regard to cookie handling in Germany. Will this plugin be updated to reflect those changes? I am not 100% yet what has to change, but I think individual cookies (not cookie groups) need to be handled individually?

See: https://www.bmwi.de/Redaktion/DE/Pressemitteilungen/2021/05/20210528-gesetz-zum-schutz-der-privatsphaere-in-der-digitalen-welt-beschlossen.html

TTDSG = Gesetz zur Regelung des Datenschutzes und des Schutzes der Privatsphäre in der Telekommunikation und bei Telemedien

**Comment by DirkPersky** [comment]
He @landwire,

da aktuell noch unklar ist, wie das Einwilligungsmanagement aussehen soll, kann ich dir die Frage nicht verbindlich beantworten. Solange die Vorgabe übersichtlich und mit angemessenen Aufwand zu bewältigen sind, werde ich meine **Private Freizeit** weiterhin investieren, um das Projekt weiter zu entwickeln.

Zitat:
```
Mit Blick auf die viel diskutierten Cookies eröffnet das Gesetz die Möglichkeit, ein nutzerfreundliches und wettbewerbskonformes Einwilligungsmanagement zu entwickeln, das Verbraucherinnen und Verbrauchern, Unternehmen und Start-ups gleichermaßen nutzt. Die Arbeiten hieran werden wir jetzt im Austausch mit allen Akteuren aufnehmen.
```

Also warten wir mal ab, welche Reglungen sich ergeben werden. Bis dahin sollte das PlugIn weiterhin konform sein.

**Comment by DirkPersky** [comment]
he @landwire,

i have a new beta version, you can load it from Git if you want.
As example visit: https://dp-wired.de/

Greetings
Dirk

**Comment by DirkPersky** [comment]
#82
