### ISSUE TITLE
Scripts not loaded in Typo3 6.2

### ISSUE THREAD

**Issue by andihuber** [DirkPersky/typo3-dp_cookieconsent#8]
Hello,

i installed the extension via extension manager in Typo3 6.2. 
Then selected static templates on root page.

Demo-Typoscript code is in Typoscript template.

But the javascripts are not loading in frontend and the cookie consent bar is not showing.

www.kontron-electronics.de

Thank you,
BR Andreas

**Comment by DirkPersky** [comment]
Hello Andreas,

maybe there is a other, Plug-In or your template thats override the.
`page.headerData.998`

or you you dont used the `page `value for your Template.

**Comment by andihuber** [comment]
Hello Dirk,

ohh, you are right. I coincidentally use the same number at page.headerData.... **thank you** for the hint. I think that causes the problem. Will try it tomorrow.

BR Andreas
