### ISSUE TITLE
Add SameSite=Secure to cookie

### ISSUE THREAD

**Issue by npostnik** [DirkPersky/typo3-dp_cookieconsent#81]
Hi,

cookies with SameSite attribute set to None will soon be declined by some browsers. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Please adjust the setCookie function to set this attribute to Strict.
setCookie: function (e, t, o, n, i, s) {
[...]
// add SameSite strict attribute
var c = [e + "=" + t, "expires=" + r.toUTCString(), "path=" + (i || "/"), "SameSite=Strict"];

Thank you and kind regards,
Natalia

**Comment by DirkPersky** [comment]
Will be in the next release.

**Comment by npostnik** [comment]
Great, thank you!
