### ISSUE TITLE
TTDSG - 3rd Button

### ISSUE THREAD

**Issue by timelessworks** [DirkPersky/typo3-dp_cookieconsent#82]
Hi,

great extension, thank you. I use the "opt-in" layout and a german client likes to have a 3rd Button "deny all".  For the new TTDSG (01.12.2021) his data protection officer is recommending that 3rd Button "Deny all" and I'm looking for a solution. 

In Opt-In layout I get two Buttons:
1. dismiss = Save settings
2. allowall = Accept all Cookies (all checkboxes will be marked and hint closed)

in Opt-out layout
1. deny = Deny all (here I have a bug, all the checkboxes stay marked. They should unmark right?)
2. dismiss = Save settings

is it possible in a easy way to get a 3rd Button "deny all" in the "Opt-In Layout"? After analyzing I think the magic happens in the Javascript "dp_cookieconsent.js", but don't want to rewrite the JS also for update compatibility and looking for a smarter way. 

Do you have an idea?

Thank you

**Comment by DirkPersky** [comment]
He @timelessworks 

hast du einen offiziellen Text der den 3 Button fordert?
Ich habe bislang noch nichts dazu gesehen auch auf Seiten wie "https://datenschutz-generator.de/"  ist kein 3er Button hinterlegt.


LG
Dirk

**Comment by DirkPersky** [comment]
But yes i working on a complete new version of the cookie consent.

**Comment by timelessworks** [comment]
Hi Dirk,

nein ich habe die Infos von einem Datenschutzbeauftragten bekommen und verstehe es auch als Deutung des Gesetzestextes. 

"seit 01.12.2021 gilt das TTDSG.  Dieses enthält neben der EU-DSGVO eigenen Bußgeldregelungen (bis zu 300.000,00 €). Zentral gilt § 25 TTDSG: Speicherung von Informationen in der Endeinrichtung des Endnutzers oder Zugriff auf Informationen sind nur zulässig, wenn der Endnutzer […] eingewillig hat." 
 
Der Datenschutzbeauftragte sieht es so, wenn man komplett einwilligen kann und die Checkboxes gesetzt werden, muss man auch komplett widersprechen können und alle checkboxes wieder entmarkt werden. 

Beste Grüße und danke für deine Arbeit
Eike

**Comment by DirkPersky** [comment]
Jo der erste teil ist ja gegeben! 
Mit den "alle entmarken" ist gerade noch in der Entwicklung.

Ich bin aber dran ;)

LG
Dirk

**Comment by timelessworks** [comment]
Perfekt! Ich hatte noch keine Idee, wie ich den "Deny" Button ins Opt-In Layout mitreinbekomme. Das passiert auch per JS oder?

**Comment by DirkPersky** [comment]
he @timelessworks ,

im .git findest du eine neue Beta (11.4.0-beta) Version, wo ein 3er Button hinzugefügt ist.
Auf meine Seite ist es bereits eingebunden: https://dp-wired.de/

Grüße
Dirk

**Comment by timelessworks** [comment]
Great, I checked it out and it works fine in my dev area on Typo3 v10. Now I have the problem that the clients project is on Typo3 v8 and dp_cookieconsent 1.4.0 beta it is not working in this environment. Any idea for a quickfix to get this button into the opt-in layout or is it to complicated because changes on to many points?

Thanks

**Comment by DirkPersky** [comment]
U can do it manualy.

Stay using the old version of the Plugin!
Copy the Ressources folder from .git into it, and it shoud work ;)

LG
Dirk

**Comment by DirkPersky** [comment]
I will think about a version for old systems ;)

**Comment by DirkPersky** [comment]
https://github.com/DirkPersky/typo3-dp_cookieconsent/tree/v11.2

here is version for TYPO3 8LTS and 9 LTS
