### ISSUE TITLE
T3 10 - error IconRegistry while trying to install extension

### ISSUE THREAD

**Issue by asche76** [DirkPersky/typo3-dp_cookieconsent#84]
since the 2 or 3 last versions while trying to install the extension, the log throws the following error:

[Thu Jan 20 17:38:26.321885 2022] [fcgid:warn] [pid 26392] [client ....:1402] mod_fcgid: stderr: PHP Fatal error:  
Cannot use TYPO3\\CMS\\Core\\Imaging\\IconRegistry

after trying to install the ext, the whole site & backend is no more usable.

till version 11.2.0 the ext works fine.

a colleague says the reason is, that the extension is trying to embed/include the following classes again - lines 2294-2296  :
![image](https://user-images.githubusercontent.com/47745128/150384070-9bae6383-1de9-4a7a-a79f-3cb19f945dd0.png)

**Comment by DirkPersky** [comment]
How do you install the Extension?

I tried it in TYPO3 10.4.23 and 11.5.5 without any issue.
Installed via classic symlink version.

**Comment by asche76** [comment]
only via extension manager - best regards

**Comment by DirkPersky** [comment]
I added a new Release 11.6.0 the problem should be solved.

**Comment by asche76** [comment]
11.6.0 works fine - deluxe - thank you very much
