### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by rimmeh** [DirkPersky/typo3-dp_cookieconsent#85]
Hi,

i updated from 11.1.1 to 11.6.0.

PHP 7.4

Typo3 10.4.23.

After Upgrading the Frontend throws an Error:

`(1/1) ArgumentCountError
Too few arguments to function TYPO3\CMS\Extbase\Persistence\Repository::__construct(), 0 passed in /var/customers/webs/nndev/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3480 and exactly 1 expected

in /var/customers/webs/nndev/typo3/sysext/extbase/Classes/Persistence/Repository.php line 71
     * Constructs a new Repository
     *
     * @param \TYPO3\CMS\Extbase\Object\ObjectManagerInterface $objectManager
     */
    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
        $this->objectType = ClassNamingUtility::translateRepositoryNameToModelName($this->getRepositoryClassName());
    }`

**Comment by DirkPersky** [comment]
Hi

I testet it on a dev projekt TYPO 10.4.23 too and there it works.

Can u trie to "Maintenance > Dump autoload" , "Maintenance > Analyse database" and "Maintenance  > Flush cache" ?
Than it shoud work.

**Comment by Hawkeye1909** [comment]
Hi Dirk,

I had the same issue and tried your suggestions:

- Maintenance > Dump autoload: error persists
- Maintenance > Analyse database: nothing found
- Maintenance > Flush cache: error is gone
