### ISSUE TITLE
Translating the cookie list view (GER) / changing the template not possible

### ISSUE THREAD

**Issue by kriemhildt** [DirkPersky/typo3-dp_cookieconsent#86]
Hello there,
I'm currently trying to translate the table that shows the cookie list.
First, I set the template path in the constants:
```
plugin.tx_cookieconsent.view.partialRootPath = EXT:myext/Resources/Private/Partials/dp_cookieconsent/
plugin.tx_cookieconsent.view.templateRootPath = EXT:myext/Resources/Private/Templates/dp_cookieconsent/
plugin.tx_cookieconsent.view.layoutRootPath = EXT:myext/Resources/Private/Layouts/dp_cookieconsent/
```
It might be that the general problem is already existent at this point. But I can't find it. Nevertheless this is how I went on:

Because there currently is no german translation for the thead table rows I then went into the template and changed the translation key to the path of my extension and the language files within.
```
 <f:translate key="LLL:EXT:myext/Resources/Private/Language/de.locallang.xlf:cookie.name"/>
```
 I created the corresponding language file in my extension and added the missing items. Like this:
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<xliff version="1.0">
    <file source-language="en" datatype="plaintext" original="messages" date="2015-09-19T09:11:39Z" product-name="theme_t3kit">
		<header/>
		<body>
            <trans-unit id="cookie.name">
                <source>Cookies</source>
                <target>Cookies</target>
            </trans-unit>
            <trans-unit id="cookie.category">
                <source>Category</source>
                <target>Kategorie</target> // this for example is not shown in the FE
            </trans-unit>
...
```
As I said, maybe the problem started way before altering the template file, because I can't make **any** changes to the template.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/88493491/151368611-c3ab6e21-d1a8-4d9d-a892-6d08e15ebaa9.png">

But I know for sure that clearing the cache isn't the problem.

Any help would be much appreciated :)

**Comment by asche76** [comment]
would use the ext translate_locallang. with the u can easy translate all labels:

![image](https://user-images.githubusercontent.com/47745128/151382568-d0bfda91-631b-4328-a21a-b18790be1af6.png)

![image](https://user-images.githubusercontent.com/47745128/151382655-334c04e1-9094-487a-be7c-527c0742c87b.png)

![image](https://user-images.githubusercontent.com/47745128/151382392-d60d60a6-5e69-42b3-be7a-9f1de47a9fc7.png)

**Comment by kriemhildt** [comment]
@asche76 thanks for the tip! I can see the benefits of this approach. But I was hoping to achieve this without an additional extension.

**Comment by asche76** [comment]
problem with this method is, after dp_cookie ext update the new labels are reverted to the default ones. i thought the translation locallang ext would have saved the changes as some kind of overlay or abstraction somewhere -.-

**Comment by DirkPersky** [comment]
fixed in next release
