### ISSUE TITLE
Text link revocation no longer possible

### ISSUE THREAD

**Issue by Nesfiran** [DirkPersky/typo3-dp_cookieconsent#87]
I have updated the version from version 10.7.0 to 11.5.0.
I use a text link to open the revocation settings.
This used to work with the following function.

`window.DPCookieConsent.popup.revokeChoice();`

Has this been changed / removed? I would like to stay with the text link in any case.

**Error**
window.DPCookieConsent.popup.revokeChoice is not a function

Can you give me a hint?

**Comment by DirkPersky** [comment]
The new function for this is:
```window.DPCookieConsent.popup.revoke()```

**Comment by Nesfiran** [comment]
Thanks for the hint it works now.
