### ISSUE TITLE
Dynamic checkboxes are not saved by the new javascript code

### ISSUE THREAD

**Issue by jcdirks** [DirkPersky/typo3-dp_cookieconsent#88]
After the rewrite in version v11.6.0, additional checkboxes are not saved to the cookie anymore. 

The array of available cookies is now static, see https://github.com/DirkPersky/npm-dp_cookieconsent/blob/b0c89844ddc4b349349aa2c6eb7684b4647537cb/src/js/dp_cookieconsent.js#L218. Thus, only the marketing and the statistics checkbox are saved to the cookie.

A work-around is to copy the script from Resources/Public/JavaScript/dp_cookieconsent.js to the own sitepackage, add the cookie to the array and override the extension's script by setting 
`page.includeJSFooter.dp_cookieconsent = EXT:MYSITEPACKAGE/Resources/Public/JavaScript/Dist/dp_cookieconsent.js`

Of course, this approach is not suitable for further updates of the extensiin. A way to add dynamic checkboxes to the options array in a dynamic way would be highly appreciated.

**Comment by DirkPersky** [comment]
He you dont need that.

You only have to change the initial typosctipt

```
page.footerData.998.20.settings.checkboxes.NEWCHECKBOX = false
```

**Comment by DirkPersky** [comment]
Is fixed with the new JS and in relese

**Comment by jcdirks** [comment]
Thanks a lot for the speedy fix, works just fine now!
