### ISSUE TITLE
Revokable doesn't work

### ISSUE THREAD

**Issue by zchakarov** [DirkPersky/typo3-dp_cookieconsent#9]
I want to hide the revoke button in front-end and i tried to set revokable to false, but it didn't help... What is the function of 'revolke' then?

**Comment by DirkPersky** [comment]
it is piped directly to [Cookie Consent Referenzes](https://cookieconsent.osano.com/documentation/javascript-api/#revoke_options)

But i take your idea for the next release.

**Comment by DirkPersky** [comment]
shoud work now
