### ISSUE TITLE
Cookieconsent not stopping loading of js

### ISSUE THREAD

**Issue by kriemhildt** [DirkPersky/typo3-dp_cookieconsent#90]
Hey there,

I'm having trouble with a Twitter iframe: The JS in the blocked HTML is loaded, even if the cookie isn't accepted. I'm using the good old
``
<dp-content
    data-cookieconsent="statistics"
    class="dp--iframe">
    <a>Tweets</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</dp-content>
``
in an HTML CE but it won't work, as my network analysis shows me all the images and the JS being loaded but there is (of course) only the overlay to be seen. Help is much appreciated! 

Thanks for your time!

**Comment by DirkPersky** [comment]
if you want use it plain u need to use the Content Module.
Else i recommend to change your code

```
<a>Tweets</a> 
<script data-ignore="1" data-cookieconsent="statistics" type="text/plain" async data-src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
