### ISSUE TITLE
Is it posssible die deactivate checkboxes?

### ISSUE THREAD

**Issue by schorsch8878** [DirkPersky/typo3-dp_cookieconsent#91]
Hello, i would like to deactivate/hide checkboxes. In older Versions i had noch checkboxes with my current settings. I didn't found anything in doc.

Many thanks

plugin.tx_cookieconsent.settings.url = 13
plugin.tx_cookieconsent.settings.dismissOnScroll = 0
plugin.tx_cookieconsent.settings.type = opt-in
plugin.tx_cookieconsent.settings.palette.popup.background = #333
plugin.tx_cookieconsent.settings.palette.popup.text = #FFFFFF
plugin.tx_cookieconsent.settings.palette.button.background = #616161
plugin.tx_cookieconsent.settings.palette.button.text = #FFFFFF
plugin.tx_cookieconsent.settings.position = bottom-right
plugin.tx_cookieconsent.settings.overlay.notice = true
plugin.tx_cookieconsent.settings.overlay.button.background = #616161

**Comment by DirkPersky** [comment]
Not as build in, cause of german cookie law.

But you can do it as workaround.
https://docs.typo3.org/p/dirkpersky/typo3-dp_cookieconsent/main/en-us/Developer/Checkboxes.html

```
page.footerData.998.20.settings.checkboxes.marketing >
page.footerData.998.20.settings.checkboxes.statistics >
```

greetings
