### ISSUE TITLE
TypoScript conditions are ignored

### ISSUE THREAD

**Issue by kriemhildt** [DirkPersky/typo3-dp_cookieconsent#92]
Hi there,

I have the following problem:
I'm working on a project with multiple page trees, which both use cookie consent, but have different texts and settings. Since updating to 11.6, settings for my second page tree seem to be ignored.

This is how I set up my constants.typoscript

```
[177 in tree.rootLineIds]
plugin.tx_cookieconsent.settings.type = info
plugin.tx_cookieconsent.settings.palette.popup.background = #000
plugin.tx_cookieconsent.settings.palette.popup.text = #fff
plugin.tx_cookieconsent.settings.palette.button.background = #6d9907
plugin.tx_cookieconsent.settings.palette.button.text = #fff
[end]
```

And this is my plugin.typoscript:

```
[177 in tree.rootLineIds]
plugin.tx_dp_cookieconsent._LOCAL_LANG {
    de {
        message = Diese Website benutzt Cookies, die für den technischen Betrieb der Website erforderlich sind und stets gesetzt werden.
        dismiss = Ich habe verstanden.
    }
}
[end]
```

But in the frontend there are only the full English text and all checkboxes.

I'm working with TYPO3 v10.4.27, dp_cookieconsent v11.6.1. The pages are translated to German as well as all extensions.#91 

Help is much appreciated :)

**Comment by DirkPersky** [comment]
Moin Moin,

a)
The type `plugin.tx_cookieconsent.settings.type = info` didn't work anymore.
That is gone since version `11.4.0` becouse of the german data privacy. (and my understanding of it)

b)
The translation i take a look on it, thank for reporting.


Greetings
Dirk

**Comment by DirkPersky** [comment]
On mysite it works to change the translations:
```
plugin.tx_dp_cookieconsent._LOCAL_LANG {
    de {
        message = Diese Webseit
    }
}
```
![image](https://user-images.githubusercontent.com/1736266/174641483-0f7e6dd0-f30b-4f2f-b7a6-2acf4a219cba.png)
