### ISSUE TITLE
Ghostery prevent the JS file from loading

### ISSUE THREAD

**Issue by ste101** [DirkPersky/typo3-dp_cookieconsent#95]
With ghostery dp_cookieconsent.js will be blocked.
Also the button with the finger print will be set to display: none with this rule:
`.cc-revoke, .cc-window.cookie, .cc-window.cookie-model, [href*="postlnk.com"], [href*="passtechusa.com"], [href*="librateam.net"]
`

Would it be possible to rename problematic things?

**Comment by DirkPersky** [comment]
#102 i removed unused class .cc-revoke from revoke button.

Unfortunately I would have to rename the wohl extension to get the JS loaded with "ghostery".
But u can enable the JS & CSS compression in typoscript

```
config.compressJs = 1
config.compressCss = 1
```

After that the JS & CSS will be loaded again. (in my tests)
