### ISSUE TITLE
forceAccept doesn’t fire dp--cookie-accept

### ISSUE THREAD

**Issue by romangebath** [DirkPersky/typo3-dp_cookieconsent#97]
I have a map, that I embed using the overlay feature. But I can only initialize the map, after the cookies are accepted. This has nothing to do with cookies per se, but the map won’t be rendered correctly, if it is initalized while still been hidden by the overlay. 

Therefore I use the `dp--cookie-accept` and `dp--cookie-accept-init` events to run the initialisation code after the cookies are accepted. This works fine when using the regular consent popup. But when the user clicks on the accept button in the overlay, then it won’t be initlaized.

If I understood correctly, the overlay uses the function `DPCookieConsent.forceAccept()`. It seems, that this function won't fire the `dp--cookie-accept` event, although it should. I only have minified code, so it’s a litte hart to see the inner functionality, but I didn't find a dispatchEvent in the code for the forceAccept code, so I guess this is a bug. Am I right?

**Comment by DirkPersky** [comment]
He the complete JS-Code can be found in the NPM project `https://github.com/DirkPersky/npm-dp_cookieconsent/tree/master/src`

I will take a look into it, with in the next week

**Comment by DirkPersky** [comment]
But why u dont use the "dp--cookie-fire" event for that?

**Comment by romangebath** [comment]
Well, I didn’t think about it. To be honest, I didn't understand the description of this event until now. But I tried using it, and this event won't be fired either.

I think the problem is, that the events are only triggered when clicking on either of the dialog buttons. But forceAllow and forceDeny use the `save` function. this function doesn't fire any event:

https://github.com/DirkPersky/npm-dp_cookieconsent/blob/6cad1ebd1ea02bf9357c16c8f05bb2d1366a4605/src/js/dp_cookieconsent.js#L574

But as this function can change the status, it should fire the appropriate events.

**Comment by romangebath** [comment]
Created a Pull Request to fix the typo:
https://github.com/DirkPersky/npm-dp_cookieconsent/pull/27
