### ISSUE TITLE
No backend options for cookies?

### ISSUE THREAD

**Issue by ProWebs** [DirkPersky/typo3-dp_cookieconsent#99]
Hello, 

i installed your extension 11.2.1 on typo3 8.7.32 and it shows outputs on frontend, but i can't finde any way to create cookies in my backend. There is no entry on list or page.

I also looked at your documentation but this doens't look very complete and doesn't help me here.

Hopefully you can give me a hint. Maybe there is also a bug ... i don't kown.

Thanks.

**Comment by DirkPersky** [comment]
Backend options are not in that Version, it comes with Version 11.3.0
